version: 3

services:
  ze-challenge-larissa-monteiro:
    image: ze-challenge-larissa-monteiro
    build: .
    environment:
      NODE_ENV: production
    ports: "5050:5050"
    volumes:
      - ./usr/app
    links:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
